More guards.

diff --git a/bin/deps b/bin/deps
--- a/bin/deps
+++ b/bin/deps
@@ -6,6 +6,16 @@ if ! [ -x "$(command -v wget)" ]; then
   exit 1
 fi
 
+if ! [ -x "$(command -v unzip)" ]; then
+  echo 'Error: unzip is not installed.' >&2
+  exit 1
+fi
+
+if ! [ -x "$(command -v npm)" ]; then
+  echo 'Error: npm is not installed.' >&2
+  exit 1
+fi
+
 if ! [ -x "$(command -v composer)" ]; then
   . $HOME/.dotfiles/bin/install_composer
 fi
